on:
  push:
    branches:    
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '*'
      - uses: actions/configure-pages@v2
      - run: npm update
      - run: npx @ca-plant-list/ca-plant-list
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./output
          destination: ./_site
      - uses: actions/upload-pages-artifact@v1
